src/chapter6/beans/Comment.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {

    private int id;
    private String text;
    private int userId;
    private int messageId;
    private Date createdDate;
    private Date updatedDate;

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public int getUser_Id() {
		return userId;
	}
	public void setUser_Id(int user_Id) {
		this.userId = user_Id;
	}
	public int getMessage_Id() {
		return messageId;
	}
	public void setMessage_Id(int message_Id) {
		this.messageId = message_Id;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	public String[] getSplitedText() {
		return text.split("\n");
	}


}

src/chapter6/controller/EditServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Message;
import chapter6.beans.UserMessage;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/edit" })
public class EditServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

    	HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

    	String messageId = request.getParameter("messageId");
    	if(!check(messageId, errorMessages)) {
    		session.setAttribute("errorMessages", errorMessages);
            response.sendRedirect("./");
            return;
    	}

    	UserMessage messages = new MessageService().edit(messageId);
    	if(!messageId.matches("^[0-9]+$") || messages == null) {
    		errorMessages.add("不正なパラメーターが入力されました");
    		session.setAttribute("errorMessages", errorMessages);
            response.sendRedirect("./");
            return;
    	}



    	//リクエストパラメータにmessagesを入れてedit.jspへ移動。
    	request.setAttribute("messages", messages);
    	request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }

    private boolean check(String messageId, List<String> errorMessages) {

        if(StringUtils.isEmpty(messageId) || !messageId.matches("^[0-9]+$")) {
        	errorMessages.add("不正なパラメーターが入力されました");
        	return false;
        }
        return true;
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

    	HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

        String text = request.getParameter("text");

        Message message = getMessage(request);
        if (!isValid(text, errorMessages)) {
            session.setAttribute("errorMessages", errorMessages);
            request.setAttribute("messages", message);
            request.getRequestDispatcher("/edit.jsp").forward(request, response);
            return;

        }


        new MessageService().update(message);
        request.setAttribute("messages", message);


        response.sendRedirect("./");
    }


	private Message getMessage(HttpServletRequest request)
			throws IOException, ServletException {

		Message message = new Message();
		message.setText(request.getParameter("text"));
		message.setId(Integer.parseInt(request.getParameter("id")));
		return message;
	}

	 private boolean isValid(String text, List<String> errorMessages) {

		 if (StringUtils.isBlank(text)) {
			 errorMessages.add("メッセージを入力してください");
	     } else if (140 < text.length()) {
	         errorMessages.add("140文字以下で入力してください");
	     }
	     if (errorMessages.size() != 0) {
	    	 return false;
	     }

	     return true;
	 }
}

src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        String accountOrEmail = request.getParameter("accountOrEmail");
        String password = request.getParameter("password");

        User user = new UserService().select(accountOrEmail, password);
        if (user == null) {
            List<String> errorMessages = new ArrayList<String>();
            errorMessages.add("ログインに失敗しました");
            request.setAttribute("errorMessages", errorMessages);
            request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }

        HttpSession session = request.getSession();
        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }
}

src/chapter6/controller/SettingServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.exception.NoRowsUpdatedRuntimeException;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/setting" })
public class SettingServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        User loginUser = (User) session.getAttribute("loginUser");

        User user = new UserService().select(loginUser.getId());

        request.setAttribute("user", user);
        request.getRequestDispatcher("setting.jsp").forward(request, response);
    }

    //ユーザー情報を更新しているメソッド。
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

        User user = getUser(request);
        //isvalidのメソッドを呼び出してtrueなら実行。48行目でUserServiceを呼び出し場面が移る。
        if (isValid(user, errorMessages)) {
            try {
                new UserService().update(user);
            } catch (NoRowsUpdatedRuntimeException e) {
                errorMessages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
            }
        }

        if (errorMessages.size() != 0) {
            request.setAttribute("errorMessages", errorMessages);
            request.setAttribute("user", user);
            request.getRequestDispatcher("setting.jsp").forward(request, response);
            return;
        }

        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }

    //変数userにname,account,passwordなどを格納してるメソッド。
    private User getUser(HttpServletRequest request) throws IOException, ServletException {

        User user = new User();
        user.setId(Integer.parseInt(request.getParameter("id")));
        user.setName(request.getParameter("name"));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setEmail(request.getParameter("email"));
        user.setDescription(request.getParameter("description"));
        return user;
    }

    //バリデーションで値をチェックしてるメソッド。
    private boolean isValid(User user, List<String> errorMessages) {

        String name = user.getName();
        String account = user.getAccount();
        String email = user.getEmail();
        User userData = new UserService().select(account);

        if (!StringUtils.isEmpty(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }
        if (StringUtils.isEmpty(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");
        }

        if(userData != null && user.getId() != userData.getId()) {
            errorMessages.add("そのアカウント名は重複しているため登録できません。");
        }

        if (!StringUtils.isEmpty(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/SignUpServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }



    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        List<String> errorMessages = new ArrayList<String>();

        User user = getUser(request);
        if (!isValid(user, errorMessages)) {
            request.setAttribute("errorMessages", errorMessages);
            request.getRequestDispatcher("signup.jsp").forward(request, response);
            return;
        }
        new UserService().insert(user);
        response.sendRedirect("./");
    }

    private User getUser(HttpServletRequest request) throws IOException, ServletException {

        User user = new User();
        user.setName(request.getParameter("name"));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setEmail(request.getParameter("email"));
        user.setDescription(request.getParameter("description"));
        return user;
    }
//バリデーションで真偽をしてるメソッド
    private boolean isValid(User user, List<String> errorMessages) {

    String name = user.getName();
        String account = user.getAccount();
        String password = user.getPassword();
        String email = user.getEmail();
        User userID = new UserService().select(account);

        if (!StringUtils.isEmpty(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }

        if (StringUtils.isEmpty(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");
        }

        if(userID != null) {
            errorMessages.add("そのアカウント名は重複しているため登録できません。");
        }


        if (StringUtils.isEmpty(password)) {
            errorMessages.add("パスワードを入力してください");
        }

        if (!StringUtils.isEmpty(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/TopServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter6.beans.User;
import chapter6.beans.UserComment;
import chapter6.beans.UserMessage;
import chapter6.service.CommentService;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class TopServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		boolean isShowMessageForm = false;
        User user = (User) request.getSession().getAttribute("loginUser");
        if (user != null) {
            isShowMessageForm = true;
        }

        //String型のuser_idの値をrequest.getParameter("user_id")でJSPから受け取るように設定
        String userId = request.getParameter("user_id");
        String start = request.getParameter("start");
        String end = request.getParameter("end");



        // MessageServiceのgetMessageに引数としてString型のuser_idを追加
        List<UserMessage> messages = new MessageService().select(userId, start, end);
        List<UserComment> comments = new CommentService().select();


        request.setAttribute("start", start);
        request.setAttribute("end", end);
        request.setAttribute("messages", messages);
        request.setAttribute("comments", comments);
        request.setAttribute("isShowMessageForm", isShowMessageForm);
        request.getRequestDispatcher("/top.jsp").forward(request, response);



	}
}

WebContent/edit.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ page import="chapter6.beans.Message" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>つぶやき編集画面</title>
        <link href="./css/style.css" rel="stylesheet" type="text/css">

    </head>
	<body>


		<c:if test="${ not empty errorMessages}">
			<div class="errorMessages">
				<ul>
        			<c:forEach items="${errorMessages}" var="errorMessage">
        				<li><c:out value="${errorMessage}" />
       				</c:forEach>
       			</ul>
       			<c:remove var="errorMessages" scope="session" />
       		</div>
       	</c:if>



		<form action="edit" method="post">
			<div class="messages">
					<div class="message">
						<div class="account-name">
						</div>
						<div class="text">
							つぶやき
							<div class="form-area">
           						<textarea name="text" cols="100" rows="5" class="tweet-box"><c:out value="${messages.text}" /></textarea>
           						<input type = "hidden" name = "id" value = "${messages.id}">
							</div>
						</div>
						<div class="date">
							<fmt:formatDate value="${messages.createdDate}"
								pattern="yyyy/MM/dd HH:mm:ss" />
						</div>
						<input type="submit" value="更新">

					</div>
			</div>
		</form>
		<br>
		<br>
		<br>
		<a href="./">戻る</a>
		<br>
		<br>
		<div class="copyright"> Copyright(c)SatoKyohei</div>
	</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    	<link href="./css/style.css" rel="stylesheet" type="text/css">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ログイン</title>
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>

            <form action="login" method="post"><br />
                <label for="accountOrEmail">アカウント名かメールアドレス</label>
                <input name="accountOrEmail" id="accountOrEmail"/> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <input type="submit" value="ログイン" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright"> Copyright(c)YourName</div>
        </div>
    </body>
</html>

WebContent/setting.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>${loginUser.account}の設定</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="setting" method="post"><br />
                <input name="id" value="${user.id}" id="id" type="hidden"/>

                <label for="name">名前</label>
                <input name="name" value="${user.name}" id="name"/>（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="account">アカウント名</label>
                <input name="account" value="${user.account}" /><br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <label for="email">メールアドレス</label>
                <input name="email" value="${user.email}" id="email"/> <br />

                <label for="description">説明</label>
                <textarea name="description" cols="35" rows="5" id="description"><c:out value="${user.description}" /></textarea> <br />

                <input type="submit" value="更新" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright"> Copyright(c)Your Name</div>
        </div>
    </body>
</html>

WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>ユーザー登録</title>
    </head>
    <link href="./css/style.css" rel="stylesheet" type="text/css">
    <body>
        <div class="main-contents">


            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="signup" method="post"><br />
                <label for="name">名前</label>
                <input name="name" id="name" />（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="account">アカウント名</label>
                <input name="account" id="account" /> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password" /> <br />

                <label for="email">メールアドレス</label>
                <input name="email" id="email" /> <br />

                <label for="description">説明</label>
                <textarea name="description" cols="35" rows="5" id="description"></textarea> <br />
                <input type="submit" value="登録" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright">Copyright(c)Your Name</div>
        </div>
    </body>
</html>

WebContent/top.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ page import="chapter6.beans.Message" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>簡易Twitter</title>
        <link href="./css/style.css" rel="stylesheet" type="text/css">
        <script src="js/jquery-3.6.0.min.js"></script>
        <script src="js/jquery-3.6.0.js"></script>
        <script src="js/test.js"></script>
    </head>
    <body>
        <div class="main-contents">
            <div class="header">
            	<c:if test="${ empty loginUser }">
                	<a href="login">ログイン</a>
                	<a href="signup">登録する</a>
                 </c:if>
                 <%--loginUserがいれば表示。ホーム画面のブロック --%>
                 <c:if test="${ not empty loginUser }">
      			 	<a href="./">ホーム</a>
       			 	<a href="setting">設定</a>
      			  	<a href="logout">ログアウト</a>
  				 </c:if>
            </div>


			<div style="display:inline-flex">
            	<form action="./" method="get">
            		<label for="start">日付</label>
            		<input type="date" name="start" id=start value="${start}">～
            		<label for="end"></label>
            		<input type="date" name="end" id=end value="${end}" />
            		<input type="submit" value="絞込"></input>
            	</form>
            </div>


			<%--loginUserがいれば表示。ホーム画面の表示。 --%>
            <c:if test="${ not empty loginUser }">
            	<div class="profile">
       				<div class="name"><h2><c:out value="${loginUser.name}" /></h2></div>
        			<div class="account">@<c:out value="${loginUser.account}" /></div>
        			<div class="description"><c:out value="${loginUser.description}" /></div>
    			</div>
			</c:if>

			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="errorMessage">
							<li><c:out value="${errorMessage}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session" />
			</c:if>

			<%--ホーム画面でつぶやきの枠を作っているブロック。messageサーブレットへpost送信 --%>
			<div class="form-area">
    			<c:if test="${ isShowMessageForm }">
        			<form action="message" method="post">
            			いま、どうしてる？<br />
            			<textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
            			<br />
            			<input type="submit" value="つぶやく">（140文字まで）
        			</form>
    			</c:if>
			</div>

             <%-- アカウントとメッセージを表示させる処理、ここを変える --%>
			<div class="messages">
				<c:forEach items="${messages}" var="message">
					<div class="message">
						<div class="account-name">								<span class="account">
							<a href="./?user_id=<c:out value="${message.userId}"/> ">
							<c:out value="${message.account}" /></a></span>
							<span class="name"><c:out value="${message.name}" /></span>
						</div>
						<c:forEach var="edit" items="${message.splitedText}">
								 	<div>${edit}</div>
						</c:forEach>
						<div class="date">
							<fmt:formatDate value="${message.createdDate}"
								pattern="yyyy/MM/dd HH:mm:ss" />
						</div>

						<div style="display:inline-flex">
							<form action = "edit" method = "get">
								<c:if test="${loginUser.id == message.userId }">
									<input type="hidden" name="messageId"  value="${message.id}"/>  <%-- --%>
									<input type="submit"  value="編集" >
								</c:if>
								&nbsp;
							</form>

							<form action = "deleteMessage" method = "post">
								<c:if test="${loginUser.id == message.userId }">
									<input type="hidden" name="deleteId"  value="${message.id}"  />
									<input type="submit"   value="削除" id="delete" >
								</c:if>

							</form>
							<br>
						</div>

						<c:forEach items="${comments}" var="comment">
							<c:if test="${message.id == comment.messageId}">
								<div class="account-name">
									<span class="account">
										<a href="./?user_id=<c:out value="${comment.userId}"/> ">
										<c:out value="${comment.account}" /></a>
									</span>
									<span class="name"><c:out value="${comment.name}" /></span>
								</div>
								<c:forEach var="reply" items="${comment.splitedText}">
								 	<div>${reply}</div>
								</c:forEach>
								<div class="date">
									<fmt:formatDate value="${comment.createdDate}"
										pattern="yyyy/MM/dd HH:mm:ss" />
								</div>
							</c:if>
						</c:forEach>

						<br><br>

						<div>
							<c:if test="${ not empty loginUser }">
							<form action = "comment" method = "post">
							 	返信<br>								<%--replyボックスにクラス変更 --%>
							 	<textarea name="text" cols="100" rows="5" class="reply-box"></textarea>
							 	<input type="hidden" name="messageId"  value="${message.id}" />
							 	<input type="hidden" name="userId"  value="${loginUser.id}"/>
							 	 <input type="submit"  value="返信" ><br><br>

							</form>
							</c:if>
						</div>
					</div>
				</c:forEach>
			</div>

			<br>
			<br>
			<div class="copyright"> Copyright(c)SatoKyohei</div>
        </div>
    </body>
</html>